doctrine:
    dbal:
        driver: '%env(DB_DRIVER)%'
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        charset: '%env(resolve:DB_CHARSET)%'
        server_version: '%env(resolve:DB_SERVER_VERSION)%'

        path: '%env(resolve:DB_PATH)%' # Only used if DB_DRIVER is SQLite

        # Specific configuration for the database (distinguish between databases)
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        quote_strategy: doctrine.orm.quote_strategy.ansi        
        auto_mapping: false
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        report_fields_where_declared: true
