name: Docker Compose Database Compatibility Matrix

on:
  push:
   branches:
     - main

jobs:
  test-compose:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - db: postgres
            app_port: 8081
          - db: mariadb
            app_port: 8082
          - db: sqlite
            app_port: 8083

    env:
      TAG: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Start ${{ matrix.db }} stack
        run: docker compose -p ${{ matrix.db }} -f doc/deploy/docker-compose.${{ matrix.db }}.yml up -d
        env:
          APP_PORT: ${{ matrix.app_port }}

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app to be available at http://localhost:${{ matrix.app_port }}"
          for i in {1..30}; do
            if curl -s http://localhost:${{ matrix.APP_PORT }} | grep -q '<!DOCTYPE'; then
              echo "App is up!"
              exit 0
            fi
            echo "Waiting..."
            sleep 3
          done
          echo "App did not become ready in time" >&2
          docker compose -f doc/deploy/docker-compose.${{ matrix.db }}.yml logs
          exit 1

      - name: Dump Docker Compose logs on failure
        if: failure()
        run: |
          # Print all service logs for debugging
          docker compose -p ${{ matrix.db }} \
            -f doc/deploy/docker-compose.${{ matrix.db }}.yml \
            logs

      - name: Stop services
        if: always()
        run: docker compose -f doc/deploy/docker-compose.${{ matrix.db }}.yml down -v
